// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_message from "./routes/api/message.ts";
import * as $index from "./routes/index.tsx";
import * as $Chat from "./islands/Chat.tsx";
import * as $Chatbox from "./islands/Chatbox.tsx";
import * as $Login from "./islands/Login.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/message.ts": $api_message,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/Chat.tsx": $Chat,
    "./islands/Chatbox.tsx": $Chatbox,
    "./islands/Login.tsx": $Login,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
